{
    "affected": [
        {
            "package": {
                "ecosystem": "Photon OS:3.0",
                "name": "apache-tomcat",
                "purl": "pkg:rpm/vmware/apache-tomcat?distro=photon-3"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "8.5.51-5.ph3"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        },
        {
            "package": {
                "ecosystem": "Photon OS:3.0",
                "name": "python3",
                "purl": "pkg:rpm/vmware/python3?distro=photon-3"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "3.7.5-8.ph3"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        }
    ],
    "id": "PHSA-2020-3.0-0161",
    "modified": "2023-05-14T05:24:59Z",
    "published": "2020-11-07T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-3.0-161"
        }
    ],
    "related": [
        "CVE-2020-27619",
        "CVE-2020-13943"
    ]
}