{
    "affected": [
        {
            "package": {
                "ecosystem": "Photon OS:4.0",
                "name": "unixODBC",
                "purl": "pkg:rpm/vmware/unixODBC?distro=photon-4"
            }
        },
        {
            "package": {
                "ecosystem": "Photon OS:4.0",
                "name": "unixODBC",
                "purl": "pkg:rpm/vmware/unixODBC?distro=photon-4"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "2.3.9-2.ph4"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        },
        {
            "package": {
                "ecosystem": "Photon OS:4.0",
                "name": "unixODBC",
                "purl": "pkg:rpm/vmware/unixODBC?distro=photon-4"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "0"
                        },
                        {
                            "fixed": "2.3.9-2.ph4"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "id": "PHSA-2024-4.0-0613",
    "modified": "2025-01-24T05:27:06Z",
    "published": "2024-05-18T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-4.0-613"
        }
    ],
    "related": [
        "CVE-2024-1013"
    ]
}