{
    "affected": [
        {
            "package": {
                "ecosystem": "Photon OS:4.0",
                "name": "python3-babel",
                "purl": "pkg:rpm/vmware/python3-babel?distro=photon-4"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "2.9.1-1.ph4"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        },
        {
            "package": {
                "ecosystem": "Photon OS:4.0",
                "name": "python3-babel",
                "purl": "pkg:rpm/vmware/python3-babel?distro=photon-4"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "0"
                        },
                        {
                            "fixed": "2.9.1-1.ph4"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "id": "PHSA-2021-4.0-0123",
    "modified": "2025-01-24T05:27:06Z",
    "published": "2021-11-04T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-4.0-123"
        }
    ],
    "related": [
        "CVE-2021-42771"
    ]
}