{
    "affected": [
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "unbound",
                "purl": "pkg:rpm/vmware/unbound?distro=photon-1"
            }
        },
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "binutils",
                "purl": "pkg:rpm/vmware/binutils?distro=photon-1"
            }
        },
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "mysql",
                "purl": "pkg:rpm/vmware/mysql?distro=photon-1"
            }
        },
        {
            "package": {
                "ecosystem": "photon:2.0",
                "name": "python-py",
                "purl": "pkg:rpm/vmware/python-py?distro=photon-2"
            }
        }
    ],
    "id": "PHSA-2021-0362",
    "modified": "2023-03-16T05:25:30Z",
    "published": "2021-02-24T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-1.0-362"
        },
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-2.0-362"
        }
    ],
    "related": null
}