{
    "affected": [
        {
            "package": {
                "ecosystem": "Photon OS:1.0",
                "name": "python3",
                "purl": "pkg:rpm/vmware/python3?distro=photon-1"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "3.5.6-17.ph1"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        }
    ],
    "id": "PHSA-2020-0332",
    "modified": "2022-01-26T07:02:13Z",
    "published": "2020-10-14T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-1.0-332"
        }
    ],
    "related": [
        "CVE-2020-26116"
    ]
}