{
    "affected": [
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "python3",
                "purl": "pkg:rpm/vmware/python3?distro=photon-1"
            }
        }
    ],
    "id": "PHSA-2020-0332",
    "modified": "2023-03-16T05:25:30Z",
    "published": "2020-10-14T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-1.0-332"
        }
    ],
    "related": [
        "CVE-2020-26116"
    ]
}