{
    "affected": [
        {
            "package": {
                "ecosystem": "photon:3.0",
                "name": "python-urllib3",
                "purl": "pkg:rpm/vmware/python-urllib3?distro=photon-3"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "1.25.11-2.ph3"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        }
    ],
    "id": "PHSA-2021-3.0-0266",
    "modified": "2023-03-16T05:25:30Z",
    "published": "2019-03-06T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-3.0-3"
        }
    ],
    "related": [
        "CVE-2021-33503"
    ]
}