{
    "affected": [
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "strongswan",
                "purl": "pkg:rpm/vmware/strongswan?distro=photon-1"
            }
        },
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "postgresql",
                "purl": "pkg:rpm/vmware/postgresql?distro=photon-1"
            }
        },
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "python2",
                "purl": "pkg:rpm/vmware/python2?distro=photon-1"
            }
        },
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "python3",
                "purl": "pkg:rpm/vmware/python3?distro=photon-1"
            }
        }
    ],
    "id": "PHSA-2018-0178",
    "modified": "2023-03-16T05:25:30Z",
    "published": "2018-08-23T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-1.0-178"
        }
    ],
    "related": [
        "CVE-2018-1060",
        "CVE-2018-10915",
        "CVE-2018-10811",
        "CVE-2018-1061",
        "CVE-2018-10925"
    ]
}