{
    "affected": [
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "PyYAML",
                "purl": "pkg:rpm/vmware/PyYAML?distro=photon-1"
            }
        },
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "linux",
                "purl": "pkg:rpm/vmware/linux?distro=photon-1"
            }
        },
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "gnutls",
                "purl": "pkg:rpm/vmware/gnutls?distro=photon-1"
            }
        },
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "libxslt",
                "purl": "pkg:rpm/vmware/libxslt?distro=photon-1"
            }
        },
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "linux-esx",
                "purl": "pkg:rpm/vmware/linux-esx?distro=photon-1"
            }
        }
    ],
    "id": "PHSA-2019-0224",
    "modified": "2023-03-16T05:25:30Z",
    "published": "2019-04-19T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-1.0-224"
        }
    ],
    "related": [
        "CVE-2019-7222",
        "CVE-2019-3459",
        "CVE-2017-18342",
        "CVE-2019-14898",
        "CVE-2019-3460",
        "CVE-2019-11068",
        "CVE-2019-3829"
    ]
}