{
    "affected": [
        {
            "package": {
                "ecosystem": "photon:4.0",
                "name": "python3",
                "purl": "pkg:rpm/vmware/python3?distro=photon-4"
            }
        },
        {
            "package": {
                "ecosystem": "photon:4.0",
                "name": "gnutls",
                "purl": "pkg:rpm/vmware/gnutls?distro=photon-4"
            }
        },
        {
            "package": {
                "ecosystem": "photon:4.0",
                "name": "curl",
                "purl": "pkg:rpm/vmware/curl?distro=photon-4"
            }
        }
    ],
    "id": "PHSA-2022-4.0-0240",
    "modified": "2023-03-16T05:25:30Z",
    "published": "2021-03-12T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-4.0-4"
        }
    ],
    "related": [
        "CVE-2021-28861",
        "CVE-2022-35252",
        "CVE-2021-4209"
    ]
}