{
    "affected": [
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "python2",
                "purl": "pkg:rpm/vmware/python2?distro=photon-1"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "2.7.15-14.ph1"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        },
        {
            "package": {
                "ecosystem": "photon:2.0",
                "name": "pam_tacplus",
                "purl": "pkg:rpm/vmware/pam_tacplus?distro=photon-2"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "1.4.1-2.ph2"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        }
    ],
    "id": "PHSA-2020-0280",
    "modified": "2023-04-28T05:25:06Z",
    "published": "2020-02-22T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-1.0-280"
        },
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-2.0-280"
        }
    ],
    "related": [
        "CVE-2019-9674",
        "CVE-2020-13881"
    ]
}